fix: proxy startup error about HEAD being registered already
If we register a GET handler, in recent aiohttp we no longeer need to register
a HEAD handler, and in fact if we do both, we get the error:

> RuntimeError: Added route will never be executed, method HEAD is already registered

So this change fixes the error by just not registered a HEAD handler.